project:
  type: book

book:
  title: "R Notes"
  author: "Kittipos Sirivongrungson"
  date: today
  site-url: https://lightbridge-r-notes.netlify.app
  repo-url: https://github.com/Lightbridge-KS/r-notes
  chapters:
    - index.qmd
    - vector.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: cosmo
      dark: slate
  #pdf:
    #documentclass: scrreprt



