project:
  type: book

book:
  title: "R Notes"
  author: "Kittipos Sirivongrungson"
  date: "4/8/2022"
  chapters:
    - index.qmd
    - vector.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  #pdf:
    #documentclass: scrreprt



