project:
  type: book

book:
  title: "R Notes"
  author: "Kittipos Sirivongrungson"
  date: today
  site-url: https://lightbridge-r-notes.netlify.app
  repo-url: https://github.com/Lightbridge-KS/r-notes
  chapters:
    - index.qmd
    - part: "General"
      chapters:
        - r-material.md
        - r-dev.md
    - part: "Data Science"
      chapters:
        - stats-ml.md
        - plots.md
        - table.md
    - part: "Sharing"
      chapters:
        - authoring.md
        - blog.md
        - app.md
        - api.md
    - others.md
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: cosmo #zephyr
      dark: slate
    number-sections: false
  #pdf:
    #documentclass: scrreprt



